# 프로그래밍의 오류와 예외

# 프로그래밍의 오류

- 프로그램에서 오류가 발생하면 
    - 시스템 레벨에서 프로그램에 문제를 야기하여 원치 않는 버그를 일으키거나, 
    - 심각하면 실행 중인 프로그램을 강제로 종료시키도 한다.
- 프로그래밍의 오류는 다양하지만, 크게 3가지로 나뉜다.
    - 컴파일 에러(compile-time error) : `컴파일`시에 발생하는 에러 
    - 런타임 에러(runtime error) : `실행`시에 발생하는 에러 
    - 논리적 에러(logical error) : 실행은 되지만 `의도와 다르게 동작`하는것

**컴파일 에러 (Compillation Error)**

- 컴파일 단계에서 오류 발견하면 컴파일러가 에러 메시지 출력해주는 것을 의미
- 컴파일 에러가 있다는 것은, 곧 컴파일이 안된다는 의미이며, 이는 즉 프로그램이 만들어지지 않아 `프로그램 실행 자체가 불가`하다
    - 사전에 문제를 파악할 수 있기 대문에 심각한 오류는 아니다

**런타임 에러 (Runtime Error)**

- `프로그램 실행 중에 에러가 발생`해서 잘못된 결과를 얻거나, 혹은 외부적인 요인(기계적 결함 등)으로 프로그램이 비정상적으로 종료되는 에러
- 자바에서는 런타임 에러를 두가지로 구분하였다
    - 에러(error) : 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
    - 예외(exception) : 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류 

**논리 에러 (Logic Error)**

- 버그
- `작동`은 하지만, 결과가 예상과 달라 사용자가 `의도한 작업을 수행하지 못하게` 되어 서비스 이용에 지장이 생길 수 있는 에러
- 논리적 오류는 컴퓨터 입장에서는 프로그램이 멀쩡히 돌아가는 것이니 에러 메시지를 알려주지 않는다.
    - 따라서 개발자는 프로그램의 전반적인 코드와 알고리즘을 체크 필요가 있다



# 자바의 예외

JVM은 프로그램을 실행하는 도중에 예외가 발생하면 해당 **예외 클래스로 객체를 생성**하고서 예외 처리 코드에서 예외 객체를 이용할 수 있도록 해준다


<details>
    <summary>오류 클래스 계층 구조</summary>

![](https://i.imgur.com/uckNalo.png)
</details>

<br>
<br>

# 예외

![](https://i.imgur.com/JZn4Kec.png)

![](https://i.imgur.com/rx3P1a7.png)

### **Object**
- 예외도 객체
- 모든 객체의 최상위 부모는 Object 이므로 예외의 최상위 부모도 Object

### **Throwable**
- 최상위 예외
- 하위에 Exception 과 Error 가 있음

### **Error**
- 메모리 부족이나 심각한 시스템 오류와 같이 애플리케이션에서 복구 불가능한 시스템 예외
- 애플리케이션 개발자는 이 예외를 잡으려고 해서는 안된다.
    - 상위 예외를 catch 로 잡으면 그 하위 예외까지 함께 잡는다. 따라서 애플리케이션 로직에서는 Throwable 예외도 잡으면 안되는데, 앞서 이야기한 Error 예외도 함께 잡을 수 있기 때문이다. 애플리케이션 로직은 이런 이유로 Exception 부터 필요한 예외로 생각하고 잡으면 된다.
    - 참고로 Error 도 언체크 예외

### **자바의 예외는 크게 두 가지로 나뉜다.**

### **1. Exception : 체크 예외**
- 애플리케이션 로직에서 사용할 수 있는 **실질적인 최상위 예외**
- Exception 과 그 하위 예외는 모두 컴파일러가 체크하는 체크 예외. 
    - 단 RuntimeException 은 예외로 한다.
- 컴파일러가 **예외 처리를 강제하는 예외**
    - 컴파일러가 예외처리를 제대로 하는지 확인해준다 (하지 않을시 컴파일 오류)

**장점** 
- 어느 메서드가 어떤 예외를 던지는지 명확히 알 수 있다

**사용상황**
- 주로 외부 리소스와 관련된 작업에서 발생하며, 개발자가 예외 처리를 통해 오류 상황에 대처할 수 있도록 설계되어 있다
- 예) 파일 입출력, 데이터베이스 연결 등의 경우

### **2. RuntimeException : 언체크 예외, 런타임 예외** 
- 컴파일러가 체크 하지 않는 언체크 예외
- RuntimeException 과 그 자식 예외는 모두 언체크 예외이다.
- RuntimeException 의 이름을 따라서 RuntimeException 과 그 하위 언체크 예외를 런타임 예외라고 많이 부른다. 여기서도 앞으로는 런타임 예외로 종종 부르겠다.

**RuntimeException을 상속받는 예외들**
- 컴파일러가 **예외 처리를 강제하지 않는 예외**
    - 컴파일러가 따로 검사를 해주지 않는다
- 어디서 어떤 예외가 나오는지 한눈에 보이지 않는다
- 주로 프로그래머의 실수나 논리적인 오류로 인해 발생
    - 예) 배열의 범위를 벗어난 인덱스에 접근하거나, `null` 참조를 사용하는 등의 경우

> **다양한 런타임 예외**
> ![](https://i.imgur.com/GUwOjoU.png)

||Checked Exception|Unchecked Exception|
|---|---|---|
|처리 여부|반드시 예외를 처리해야 함|명시적인 처리를 안해도 됨|
|확인 시점|컴파일 단계|런타임 단계|
|예외 종류|RuntimeException을 제외한, Exception 클래스와 그를 상속받는 하위 예외|RuntimeException 과 그 하위 예외|

---
# 예외 기본 규칙
**기본규칙 1.** 
- 예외는 잡아서 처리하거나, 처리할 수  없으면 밖으로 던져야 한다.

**기본규칙 2.** 
- 예외를 잡거나 던질 때 지정한 예외뿐만 아니라 그 예외의 자식들도 함께 처리된다.
    - 예를 들어서 Exception 을 catch 로 잡으면 그 하위 예외들도 모두 잡을 수 있다. 예를 들어서 Exception 을 throws 로 던지면 그 하위 예외들도 모두 던질 수 있다.

![](https://i.imgur.com/Tt3T8Uu.png)

**참고: 예외를 처리하지 못하고 계속 던지면 어떻게 될까?**
- 자바 main() 쓰레드의 경우 예외 로그를 출력하면서 **시스템이 종료**된다.
- 웹 애플리케이션의 경우 여러 사용자의 요청을 처리하기 때문에 하나의 예외 때문에 시스템이 종료되면 안된다. **WAS가 해당 예외를 받아서 처리하는데, 주로 사용자에게 개발자가 지정한, 오류 페이지를 보여준다.**

<br>
<br>

# 체크 예외
- Exception 과 그 하위 예외는 모두 컴파일러가 체크하는 체크 예외이다. 
    - 단 RuntimeException 은 예외로 한다.
- 체크 예외는 잡아서 처리하거나, 또는 밖으로 던지도록 선언해야한다. 
- 그렇지 않으면 컴파일 오류가 발생한다.

### **체크예외 상속**
```java
static class MyCheckedException extends Exception {
    public MyCheckedException(String message) {
        super(message);
    }
}
```
- Exception을 상속받은 예외는 체크 예외가 된다.
    - 예외가 제공하는 여러가지 기본 기능이 있는데, 그 중에 오류 메시지를 보관하는 기능도 있다. 
    - 코드에서 보는 것 처럼 생성자를 통해서 해당 기능을 그대로 사용하면 편리하다.

### **체크 예외 잡아서 처리**
```java
try {
    repository.call();
} catch (MyCheckedException e) { 
    //예외 처리 로직
}
```
- 체크 예외를 잡아서 처리하려면 catch(..) 를 사용해서 예외를 잡으면 된다.
- 여기서는 MyCheckedException 예외를 잡아서 처리한다.

### **catch는 해당 타입과 그 하위 타입을 모두 잡을 수 있다**
```java
public void callCatch() {
    try {
        repository.call();
    } catch (Exception e) {
        //예외 처리 로직 }
    }
}
```
- catch 에 MyCheckedException 의 상위 타입인 Exception 을 적어주어도 MyCheckedException 을 잡을 수 있다.
- catch 에 예외를 지정하면 해당 예외와 그 하위 타입 예외를 모두 잡아준다.
- 물론 정확하게 MyCheckedException 만 잡고 싶다면 catch 에 MyCheckedException 을 적어주어야 한다.
---
### **예외를 처리하지 않고, 밖으로 던지는 코드**
```java
public void callThrow() throws MyCheckedException {
    repository.call();
}
```
- 체크 예외를 처리할 수 없을 때는 method() throws 예외 을 사용해서 밖으로 던질 예외를 필수로 지정해주어야 한다. 
    - 여기서는 MyCheckedException 을 밖으로 던지도록 지정해주었다.
- throws 를 지정하지 않으면 컴파일 오류가 발생한다.
    - Unhandled exception: hello.jdbc.exception.basic.CheckedTest.MyCheckedException
- 체크 예외의 경우 예외를 잡아서 처리하거나 또는 throws 를 지정해서 예외를 밖으로 던진다는 선언을 필수로 해주어야 한다.

### **체크 예외의 장단점**
- 체크 예외는 예외를 잡아서 처리할 수 없을때, 예외를 밖으로 던지는 throws 예외를 필수로 선언해야 한다. 
- 그렇지 않으면 컴파일 오류가 발생한다. 이것 때문에 장점과 단점이 동시에 존재한다.
- 장점: 개발자가 실수로 예외를 누락하지 않도록 컴파일러를 통해 문제를 잡아주는 훌륭한 안전 장치이다. 
- 단점: 하지만 실제로는 개발자가 모든 체크 예외를 반드시 잡거나 던지도록 처리해야 하기 때문에, 너무 번거로운 일이 된다. 크게 신경쓰고 싶지 않은 예외까지 모두 챙겨야 한다. 추가로 의존관계에 따른 단점도 있는데 이 부분은 뒤에서 설명하겠다.

# 언체크 예외

### **체크 예외 VS 언체크 예외**
- 체크 예외: 예외를 잡아서 처리하지 않으면 항상 throws 에 던지는 예외를 선언해야 한다. 
- 언체크 예외: 예외를 잡아서 처리하지 않아도 throws 를 생략할 수 있다.

### **언체크 예외를 잡아서 처리하는 코드**
```java
try {
    repository.call();
} catch (MyUncheckedException e) { //예외 처리 로직
    log.info("error", e);
}
```
- 언체크 예외도 필요한 경우 이렇게 잡아서 처리할 수 있다.

### **언체크 예외를 밖으로 던지는 코드 - 생략 가능**
```java
public void callThrow() {
    repository.call();
}
```
- 언체크 예외는 throws 예외 를 선언하지 않아도 된다.
- 참고로 throws 예외 를 선언해도 된다.
    - 중요한 예외의 경우 이렇게 선언해두면 해당 코드를 호출하는 개발자가 이런 예외가 발생한다는 점을 IDE를 통해 좀 더 편리하게 인지할 수 있다.
    - (컴파일 시점에 막을 수 있는 것은 아니고, IDE를 통해서 인지할 수 있는 정도이다.)

### **언체크 예외의 장단점**
- 언체크 예외는 예외를 밖으로 던지는 throws 예외를 생략할 수 있다. 
- 이것 때문에 장점과 단점이 동시에 존재한다.
- 장점: 신경쓰고 싶지 않은 언체크 예외를 무시할 수 있다. 체크 예외의 경우 처리할 수 없는 예외를 밖으로 던지려면 항상 throws 예외 를 선언해야 하지만, 언체크 예외는 이 부분을 생략할 수 있다. 이후에 설명하겠지만, 신경쓰고 싶지 않은 예외의 의존관계를 참조하지 않아도 되는 장점이 있다.
- 단점: 언체크 예외는 개발자가 실수로 예외를 누락할 수 있다. 반면에 체크 예외는 컴파일러를 통해 예외 누락을 잡아준다.

<br>
<br>

# 체크 예외와 언체크(런타임) 예외는 언제 사용?

**1. 기본적으로 언체크(런타임) 예외를 사용**

**2. 체크 예외는 비즈니스 로직상 의도적으로 던지는 예외에만 사용**
- 해당 예외를 잡아서 반드시 처리해야 하는 문제일 때만 체크 예외를 사용해야 한다.    
    - 체크 예외 예)
        - 계좌 이체 실패 예외
        - 결제시 포인트 부족 예외 
        - 로그인 ID, PW 불일치 예외

# 체크 예외의 문제점
1. 체크 예외는 명시적으로 예외를 잡아서 처리하거나, 처리할 수 없을 때는 예외를 던지도록 method() throws 예외 로 선언해야 한다.
2. 실무에서 발생하는 대부분의 예외들은 서비스나 컨트롤러에서 **복구가 불가능한 시스템 예외**들이다
3. 이런 경우에 체크 예외를 사용하면 아래에서 올라온 복구 불가능한 예외를 서비스, 컨트롤러 같은 각각의 클래스가 모두 알고 있어야 한다. 
4. 그래서 **불필요한 의존관계 문제**가 발생하게 된다.

### **1. 복구 불가능한 예외**
- 처리할 수 있는 체크 예외라면 서비스나 컨트롤러에서 처리하겠지만, 
- 데이터베이스나 네트워크 통신처럼 시스템 레벨에서 올라온 예외들은 대부분 복구가 불가능하다. 
- 그리고 실무에서 발생하는 대부분의 예외들은 이런 시스템 예외들이다.

**예시**
- SQLException 예외 
    - 데이터베이스에 문제가 있어서 발생하는 예외 
        - SQL 문법에 문제가 있거나 
        - 데이터베이스 자체에 문제가 있거나
        - 데이터베이스 서버가 중간에 다운 되었을 수도 
        - 이런 문제들은 대부분 복구가 불가능하다. 
    - 대부분의 서비스나 컨트롤러는 이런 문제를 해결할 수는 없다. 
    - 따라서 이런 문제들은 일관성 있게 공통으로 처리해야 한다. 
        - 오류 로그를 남기고 개발자가 해당 오류를 빠르게 인지하는 것이 필요하다. 
        - 서블릿 필터, 스프링 인터셉터, 스프링의 ControllerAdvice 를 사용하면 이런 부분을 깔끔하게 공통으로 해결할 수 있다.

### **2. 의존 관계에 대한 문제**
![](https://i.imgur.com/fOYGYir.png)
![](https://i.imgur.com/Kinfh4H.png)
- 체크 예외는 컨트롤러나 서비스 입장에서는 본인이 처리할 수 없어도 어쩔 수 없이 throws를 통해 던지는 예외를 선언해야 한다.
```java
class Controller {
    public void request() throws SQLException, ConnectException {
        service.logic();
    }
}
  class Service {
    public void logic() throws SQLException, ConnectException {
        repository.call();
        networkClient.call();
    }
}
```
1. **서비스, 컨트롤러에서 java.sql.SQLException 을 의존**하기 때문에 문제가 된다.
    - 향후 리포지토리를 JDBC 기술이 아닌 다른 기술로 변경해서
        - SQLException > JPAException 으로 예외가 변경된다면 어떻게 될까?
2. **SQLException 에 의존하던 모든 서비스, 컨트롤러의 코드**를 JPAException 에 의존하도록 고쳐야 한다.
3. 서비스나 컨트롤러 입장에서는 어차피 본인이 처리할 수 도 없는 예외를 의존해야 하는 큰 단점이 발생하게 된다.
4. 결과적으로 OCP, DI를 통해 **클라이언트 코드의 변경 없이 대상 구현체를 변경할 수 있다는 장점이 체크 예외 때문에 발목을 잡게 된다**.

# 런타임 에러의 활용

![](https://i.imgur.com/asJlO2S.png)
- SQLException 을 런타임 예외인 RuntimeSQLException 으로 변환했다.
- ConnectException 대신에 RuntimeConnectException 을 사용하도록 바꾸었다.
- 런타임 예외이기 때문에 서비스, 컨트롤러는 해당 예외들을 처리할 수 없다면 별도의 선언 없이 그냥 두면 된다.

### **예외 전환**
- 리포지토리에서 체크 예외인 SQLException 이 발생하면 런타임 예외인 RuntimeSQLException 으로 전환해서 예외를 던진다.
- 참고로 이때 기존 예외를 포함해주어야 예외 출력시 스택 트레이스에서 기존 예외도 함께 확인할 수 있다. 예외 포함에 대한 부분은 조금 뒤에 더 자세히 설명한다.
- NetworkClient 는 단순히 기존 체크 예외를 RuntimeConnectException 이라는 런타임 예외가 발생하도록 코드를 바꾸었다.
- **참고** : 예외를 전환할 때는 꼭! 기존 예외를 포함하자
```java
public void call() {
    try {
        runSQL();
    } catch (SQLException e) {
        throw new RuntimeSQLException(e);
    } 
}
```

### **런타임 예외 - 대부분 복구 불가능한 예외**
- 시스템에서 발생한 예외는 대부분 복구 불가능 예외이다. 런타임 예외를 사용하면 서비스나 컨트롤러가 이런 복구 불가능한 예외를 신경쓰지 않아도 된다. 물론 이렇게 복구 불가능한 예외는 일관성 있게 공통으로 처리해야 한다.

### **런타임 예외 - 의존 관계에 대한 문제**
- 런타임 예외는 해당 객체가 처리할 수 없는 예외는 무시하면 된다. 따라서 체크 예외 처럼 예외를 강제로 의존하지 않아도 된다.

### **런타임 예외 구현 기술 변경시 파급 효과**
- 런타임 예외를 사용하면 중간에 기술이 변경되어도 해당 예외를 사용하지 않는 컨트롤러, 서비스에서는 코드를 변경하지 않아도 된다.
- 구현 기술이 변경되는 경우, 예외를 공통으로 처리하는 곳에서는 예외에 따른 다른 처리가 필요할 수 있다. 하지만 공통 처리하는 한곳만 변경하면 되기 때문에 변경의 영향 범위는 최소화 된다.


### **런타임 예외는 문서화를 잘해야 한다.**
- 추가로 런타임 예외는 놓칠 수 있기 때문에 문서화가 중요하다.
- 또는 코드에 throws 런타임예외를 남겨서 중요한 예외를 인지할 수 있게 해준다.
- 예) 문서에 예외 명시
    ```java
    /**
    * Make an instance managed and persistent.
    * @param entity  entity instance
    * @throws EntityExistsException if the entity already exists.
    * @throws IllegalArgumentException if the instance is not an
    *         entity
    * @throws TransactionRequiredException if there is no transaction when
    *         invoked on a container-managed entity manager of that is of type
    *         <code>PersistenceContextType.TRANSACTION</code>
    */
    public void persist(Object entity);
    ```
- 예) method() throws DataAccessException 와 같이 문서화 + 코드에도 명시
    - 런타임 예외도 throws 에 선언할 수 있다. 물론 생략해도 된다.
    - 던지는 예외가 명확하고 중요하다면, 코드에 어떤 예외를 던지는지 명시되어 있기 때문에 개발자가 IDE를 통해서 예외를 확인하가 편리하다.
    - 물론 컨트롤러나 서비스에서 DataAccessException 을 사용하지 않는다면 런타임 예외이기 때문에 무시해도 된다.
    ```java
    /**
     * Issue a single SQL execute, typically a DDL statement.
     * @param sql static SQL to execute
     * @throws DataAccessException if there is any problem
     */
    void execute(String sql) throws DataAccessException;
    ```

# 예외 포함과 스택 트레이스
- 예외를 전환할 때는 꼭! 기존 예외를 포함해야 한다. 그렇지 않으면 스택 트레이스를 확인할 때 심각한 문제가 발생한다.
```java
@Test
void printEx() {
    
    Controller controller = new Controller();

    try {
        controller.request();
    } catch (Exception e) {
        //e.printStackTrace();
        log.info("ex", e);
    }
}
```
- 로그를 출력할 때 마지막 파라미터에 예외를 넣어주면 로그에 스택 트레이스를 출력할 수 있다.
    - 예) log.info("message={}", "message", ex) , 여기에서 마지막에 ex 를 전달하는 것을 확인할 수 있다. 이렇게 하면 스택 트레이스에 로그를 출력할 수 있다.
    - 예) log.info("ex", ex) 지금 예에서는 파라미터가 없기 때문에, 예외만 파라미터에 전달하면 스택 트레이스를 로그에 출력할 수 있다.
    - System.out 에 스택 트레이스를 출력하려면 e.printStackTrace() 를 사용하면 된다. 실무에서는 항상 로그를 사용해야 한다는 점을 기억하자.

### **기존 예외를 포함하는 경우**

```java
public void call() {
    try {
        runSQL();
    } catch (SQLException e) {
        throw new RuntimeSQLException(e); //기존 예외(e) 포함 
    }
}
```

### **기존 예외를 포함하지 않는 경우**
```java
public void call() {
      try {
          runSQL();
      } catch (SQLException e) {
        throw new RuntimeSQLException(); //기존 예외(e) 제외 
    }
}
```
- 예외를 포함하지 않아서 기존에 발생한 java.sql.SQLException 과 스택 트레이스를 확인할 수 없다. 변환한 RuntimeSQLException 부터 예외를 확인할 수 있다. 만약 실제 DB에 연동했다면 DB에서 발생한 예외를 확인할 수 없는 심각한 문제가 발생한다.
- 예외를 전환할 때는 꼭! 기존 예외를 포함하자

# 예외 처리

**프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것**

- 목적 : 예외의 발생으로 인한 실행 중인 프로그램의 갑작스런 비정상적인 동작을 막고, 에러를 잡아 복구를 시도하거나 아니면 회피 하는식으로 처리를해서, 프로그램이 정상적인 실행상태를 유지할 수 있도록 하는 것

## try - catch - finally 문 

- try
    - 예외가 발생할 수 있는 코드 블록을 감싸는 데 사용
    - `try`블록 내부의 코드가 실행되다가 예외가 발생하면, 해당 예외와 일치하는 `catch` 블록으로 제어가 이동한다

- catch 
    - 예외가 발생했을 때 처리할 코드 블록을 정의하는 데 사용
    - `catch` 블록은 예외 유형에 따라 여러 개를 사용할 수 있다
        - 각 `catch` 블록은 특정 예외 유형을 처리하도록 정의되며, 발생한 예외와 일치하는 `catch` 블록이 실행된다
    - `try`블록 내부에서 예외가 발생하면 자바는 해당 예외에 해당하는 예외 객체를 생성
        - 해당 예외를 `catch`의 매개변수 e에 담아준다 🧩


``` java
try {
    // 예외가 발생할 수 있는 코드
} catch (FileNotFoundException e) {
    // FileNotFoundException 예외 처리
} catch (IOException e) {
    // IOException 예외 처리]
}
```

- finally
    - 예외가 발생하던, 발생하지 않던 무조건 실행되는 블럭
    - 어떤 예외가 발생하더라도 반드시 실행되어야 할 때 사용
    ![](https://i.imgur.com/TEublDJ.png)



> JDK 1.7부터 여러 catch 블럭을 `|` 기호를 통해서 하나의 `catch` 블럭으로 합칠 수 있게 되었다
>
> ``` java
> try {
>     // ...
> } catch (NullPointException | ArrayIndexOutOfBoundsExcetion e) {
>     // ...
> }
> ```

<br>

## 예외 처리 🧩
- `getMessage()`
    - 예외의 원인을 출력
- `toString()`
    - 예외의 종류와 원인을 출력
- `printStackTrace()`
    - 예외의 종류와 원인, 어디에서 에러가 났는지 출력(가장 상세)
    - 실행문이 내포되어있어서 출력문이 필요없음.

```java
System.out.println(e.gerMessage());
System.out.println(e.toString());
e.printStackTrace();
```

<br>
<br>

# 예외 던지기

- 예외 처리를 메소드 내부에서 직접 수행하지 않고, 메소드를 호출한 상위 호출자가 적절하게 처리할 수 있다. 이를 예외 던지기라고 부른다
    - 예외 던지기 : 메소드 내에서 발생한 예외를 해당 메소드를 호출한 곳으로 전달하여 처리할 수 있도록 하는 기능
- `throw` 키워드를 사용하여 강제로 예외를 발생시킬 수 있다
    - 이 때 `new` 생성자로 예외 클래스를 초기화하여 던져는데, 이 클래스 생성자에 입력값을 주게되면, `catch`문의 `getMessage()`메서드에서 출력할 메시지를 지정하게 된다.
- `throws` 키워드를 사용하여 상위 클래스에서 예외처리를 강제하도록 할 수 있다.

---

### `throws` / `throw`

**`throw`**
- 예외를 발생시키기 위해 사용
- 메소드 내부에서 사용되며, 실제로 예외를 발생시키는 데 사용된다.
- 생성된 예외 객체를 던져서 예외 처리 흐름을 시작한다.
- 예: `throw new FileNotFoundException("File not found.");`

**`throws`**
- 예외를 떠넘기기 위해 사용
- 메소드 선언부에 사용되며, 해당 메소드가 발생시킬 수 있는 예외를 명시한다.
- 메소드를 호출하는 쪽에서 이 메소드가 발생시킬 수 있는 예외에 대한 처리> 를 대비하도록 한다
- 예: `public void readFile() throws IOException { ... }`
---

``` java
public static void main(String[] args) {
    try {
        methodA();
    } catch (IOException e) {
        System.out.println("Caught exception: " + e.getMessage());
    }
}

public static void methodA() throws IOException {
    methodB();
}

public static void methodB() throws IOException {
    throw new IOException("An error occurred in methodB.");
}
```
1. `methodB`는 `IOException`을 발생시키고, 호출자로 전달한다.
2. `methodA`는 `methodB`를 호출하지만, 예외를 처리하지 않고 다시 호출자인 `main` 메소드로 전달한다.
3. `main` 메소드의 `try-catch` 블록에서 `IOException`을 처리한다
4. 이 과정을 통해 `methodA`, `methodB` 메서드는 예외 처리에 관여하지 않고, 호출자가 적절한 처리를 수행할 수 있다

### **예외가 발생했을 때 진행 순서**
1. `try` 블록의 실행이 중단됨
2. `catch` 블록 중에 발생한 예외를 처리할 수 있는지 찾음
   - 위에서부터 하나씩 평가
3. 예외를 처리할 수 있는 `catch` 블록이 있다면 해당 `catch` 블록안의 코드들이 실행 후 `finally` 블록 실행. `try`블록 이후의 코드들이 실행됨
4. 예외를 처할 수 있는 `catch` 블록이 없다면 `finally`블록을 실행 후 한 단계 높은 `try` 블록으로 전달


<br>

# 연결된 예외 (Chained Exception)

- 자바에서 예외 처리를 할 때, 하나의 예외가 다른 예외를 유발하거나 함께 처리해야 하는 상황을 다루기 위한 개념
- 발생한 예외를 다른 예외와 연결하여, 하나의 예외 처리 블록에서 여러 예외를 처리하는 것
- 연결된 예외를 통해 원래 발생한 예외의 원인을 추적하고, 예외 처리를 더 명확하고 효과적으로 할 수 있다

### 연결된 예외 사용 방법


- `Throwable` 클래스의 `initCause(Throwable cause)` 메소드를 사용하여 예외 객체에 원인 예외를 설정한다.
- `Throwable` 클래스의 `getCause()` 메소드를 사용하여 원인 예외를 가져온다.

``` java
try {
    // 예외를 발생시키는 코드
} catch (IOException e) {
    // IOException을 처리하면서 다른 예외가 발생하는 상황을 가정한다.
    RuntimeException runtimeException = new RuntimeException("An error occurred while handling IOException");
    runtimeException.initCause(e);
    throw runtimeException;
}
```
> 연결된 예외(chained exception)를 사용하는 또 다른 이유는 checked예외를 unchecked예외로 바꿀 수 있도록 하기 위함이다.

<br>

# 커스텀 예외

- 자바의 예외는 결국 클래스다. 따라서 예외 클래스를 상속받아서 확장시킬 수 있다.
- 커스텀 예외 클래스는 `Exception`을 상속받는 클래스를 상속받아 만들 수 있다. (`Exception`을 상속받아도 된다)

``` java
public final class UserNotFoundException extends RuntimeException {
    public UserNotFoundException() {
        super();
    }
    
    public UserNotFoundException(String message) {
        super(message);
    }
    
    public UserNOtFolundException(String message, Throwable cause) {
        super(message, cause);
    }
}

```

### SampleCode 2. 커스텀 예외_InsufficidentException
```java
                                            //컴파일 시 체크 됨
public class InsufficidentException extends Exception {
    public InsufficidentException() {}
    public InsufficidentException(String message) {
        super(message);
    }
}
```
```java
public class Account{
    
    private long balance;
    public Account(){} //생략 가능
    
    public long getBalance(){
        return balance;
    }
    
    //예금하기
    public void deposit(int money){
        balance += money;
    }
    
    //출금하기
    public void withdraw(int money) throws InsufficidentException {
        if(balance < money){
            throw new InsufficidentException("잔고부족:"+(money-balance)+"모자람");
        }
        balance -= money;
    }
}
```
```java
public class Account {
    public static void main(String[] args){
        Account account = new Account();
        
        account.deposit(1000);
        
        //account.withdraw(100); -> try catch하지 않으면 컴파일 오류남
        try {
            account.withdraw(100);
        } catch(InsufficidentException e){
            String message = e.getMessage();
            sout(message);
        }
        sout("예금액:" + account.getBalance());
        
    }
}
```

### SampleCode 1. 커스텀 예외_CustomExceptionExample

``` java
public class CustomExceptionExample {
    public static void main(String[] args) {
        try {
            validateUserInput("Invalid input");
        } catch (UserNotFoundException e) {
            System.out.println("Caught custom exception: " + e.getMessage());
        }
    }

    public static void validateUserInput(String input) throws UserNotFoundException {
        if ("Invalid input".equals(input)) {
            throw new UserNotFoundException("The provided input is invalid.");
        }
    }
}

```
---

## Exception Handling

**예외 복구**
- `try-catch`
- 예외가 발생했을 때 프로그램이 **정상적인 상태로 돌아올 수 있도록** 예외를 처리하는 방법
- 예외 상황을 해결하고 **프로그램이 계속 실행될 수 있도록** 코드를 작성하는 것이 포함된다
- 예외 복구는 대개 재시도 로직을 구현하거나, 대체 데이터를 사용하여 **프로그램이 계속 실행될 수 있는 상태를 만드는 데 사용**된다

---

**예외 처리 회피**
- `throws`
-  현재 발생한 예외를 처리하지 않고, **호출한 메소드나 상위 계층에 예외 처리를 위임**하는 방법
-  예외를 처리하는 데 필요한 지식이나 자원이 현재 메소드에 없을 때 사용할 수 있는 방법
-  남용하면 예외 처리가 전체 시스템에서 적절히 이루어지지 않을 수 있으므로 주의가 필요하다

---

**예외 전환**
- `Chained Exception`
- 발생한 예외를 새로운 예외로 변경하여 처리하는 방법으로 크게 두 가지 상황에서 사용된다
    1. 발생한 예외를 더 구체적인 예외로 변경하여, 호출자에게 더 유용한 정보를 제공하고자 할 때 사용
    2. 발생한 예외가 시스템 계층간의 의존성을 높이게 되는 경우, 의존성을 낮추기 위해 새로운 예외로 전환한다. 이를 통해 하위 계층에서 발생한 예외가 상위 계층에 영향을 주지 않도록 할 수 있다.
- 예외 전환을 사용할 때는 원래 발생한 예외를 새로운 예외의 원인(Cause)로 설정하여, 추후 디버깅이나 로그 분석 시에 원래 예외 정보를 확인할 수 있도록 해야 한다.
